name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # Picked up by dotenv-flow in airaloClient.ts
      AIRALO_AUTH_URL: ${{ secrets.AIRALO_AUTH_URL }}
      AIRALO_BASE_URL: ${{ secrets.AIRALO_BASE_URL }}
      AIRALO_CLIENT_ID: ${{ secrets.AIRALO_CLIENT_ID }}
      AIRALO_CLIENT_SECRET: ${{ secrets.AIRALO_CLIENT_SECRET }}

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Node & pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm i -g pnpm@8

      # 3. Restore pnpm store cache (speeds up cold starts)
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 4. Install deps
      - name: pnpm install
        run: pnpm install --frozen-lockfile

      # 5. Install Playwright browsers (cached automatically by the action)
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      # 6. Run the full test suite
      - name: Run tests
        run: pnpm run test
        # turn the step red when *any* test fails
        continue-on-error: false

      # 7. Upload HTML report + traces
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()        # even when tests fail
        with:
          name: playwright-report
          path: |
            playwright-report
            test-results/**/*.zip
          retention-days: 7
