name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      AIRALO_AUTH_URL:      ${{ secrets.AIRALO_AUTH_URL }}
      AIRALO_BASE_URL:      ${{ secrets.AIRALO_BASE_URL }}
      AIRALO_CLIENT_ID:     ${{ secrets.AIRALO_CLIENT_ID }}
      AIRALO_CLIENT_SECRET: ${{ secrets.AIRALO_CLIENT_SECRET }}

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Install pnpm (adds it to PATH)
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      # 3. Setup Node + **enable pnpm cache**
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4. Install deps
      - run: pnpm install --no-frozen-lockfile

      # 5. Install Playwright browsers
      - run: pnpm exec playwright install --with-deps

      # 6. Run tests
      - name: Run tests
        run: pnpm run test
        continue-on-error: false
        id: tests

      # 7. Build the static HTML (creates ./playwright-report)
      - name: Build HTML report
        run: pnpm exec playwright show-report --quiet
        if: always()

      # 8. Upload report + traces
      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report
            test-results/**/*.zip
          retention-days: 14