name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      AIRALO_AUTH_URL:      ${{ secrets.AIRALO_AUTH_URL }}
      AIRALO_BASE_URL:      ${{ secrets.AIRALO_BASE_URL }}
      AIRALO_CLIENT_ID:     ${{ secrets.AIRALO_CLIENT_ID }}
      AIRALO_CLIENT_SECRET: ${{ secrets.AIRALO_CLIENT_SECRET }}

    steps:

      # 1. checkout
      - uses: actions/checkout@v4

      # 2. Node + pnpm (with cache)
      - uses: pnpm/action-setup@v3
        with: { version: 8 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 3. deps + browsers
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm exec playwright install --with-deps

      # 4. run the whole suite
      - name: Run tests
        run: pnpm exec playwright test --config=configs/playwright.config.ts
        continue-on-error: false           # fail the job when tests fail

      # 5. (Optional) build static HTML if you *didn’t* use the html reporter
      #    Comment this out if you already generate the report in step 4.
      - name: Build HTML report
        if: always()
        run: pnpm exec playwright show-report --quiet

      # 6. upload artefacts – will always exist now
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report              # static HTML dashboard
            test-results/**/*.zip          # zipped traces
          retention-days: 14
